"""Add missing AI conversation fields

Revision ID: f53cab833865
Revises: ee8c78434472
Create Date: 2025-09-29 14:56:43.564655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f53cab833865'
down_revision: Union[str, Sequence[str], None] = 'ee8c78434472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add context_type column with a default value for existing records
    op.add_column('ai_conversations', sa.Column('context_type', sa.Enum('GENERAL', 'LOGISTICS', name='contexttype'), nullable=True))
    op.execute("UPDATE ai_conversations SET context_type = 'GENERAL' WHERE context_type IS NULL")
    op.alter_column('ai_conversations', 'context_type', nullable=False)
    op.add_column('ai_conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('ai_conversations', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # Manual type conversion for message_count with USING clause
    op.execute('ALTER TABLE ai_conversations ALTER COLUMN message_count TYPE INTEGER USING COALESCE(message_count::integer, 0)')
    # Add message_type column with a default value for existing records
    op.add_column('ai_messages', sa.Column('message_type', sa.Enum('TEXT', 'FILE_ANALYSIS', name='messagetype'), nullable=True))
    op.execute("UPDATE ai_messages SET message_type = 'TEXT' WHERE message_type IS NULL")
    op.alter_column('ai_messages', 'message_type', nullable=False)
    op.add_column('ai_messages', sa.Column('file_attachments', sa.JSON(), nullable=True))
    # Manual type conversion for role column to enum
    op.execute('ALTER TABLE ai_messages ALTER COLUMN role TYPE messagerole USING role::messagerole')
    # Manual type conversion for token_count with USING clause
    op.execute('ALTER TABLE ai_messages ALTER COLUMN token_count TYPE INTEGER USING COALESCE(token_count::integer, 0)')
    op.drop_column('ai_messages', 'attachments')
    op.add_column('shipments', sa.Column('order_number', sa.String(length=50), nullable=True))
    # Manual type conversion for creation_method column to enum
    # First drop the default value, then convert type, then set new default
    op.execute('ALTER TABLE shipments ALTER COLUMN creation_method DROP DEFAULT')
    op.execute('ALTER TABLE shipments ALTER COLUMN creation_method TYPE creationmethod USING creation_method::creationmethod')
    op.execute("ALTER TABLE shipments ALTER COLUMN creation_method SET DEFAULT 'AUTO'::creationmethod")
    op.drop_index(op.f('ix_shipments_creation_method'), table_name='shipments')
    op.create_index(op.f('ix_shipments_order_number'), 'shipments', ['order_number'], unique=True)
    op.create_foreign_key(None, 'shipments', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_index(op.f('ix_shipments_order_number'), table_name='shipments')
    op.create_index(op.f('ix_shipments_creation_method'), 'shipments', ['creation_method'], unique=False)
    op.alter_column('shipments', 'creation_method',
               existing_type=sa.Enum('AUTO', 'MANUAL', name='creationmethod'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'auto'::character varying"))
    op.drop_column('shipments', 'order_number')
    op.add_column('ai_messages', sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('ai_messages', 'token_count',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('ai_messages', 'role',
               existing_type=sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('ai_messages', 'file_attachments')
    op.drop_column('ai_messages', 'message_type')
    op.alter_column('ai_conversations', 'message_count',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('ai_conversations', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('ai_conversations', 'last_message_at')
    op.drop_column('ai_conversations', 'context_type')
    # ### end Alembic commands ###
