openapi: 3.0.3
info:
  title: Shipment API
  description: 运单管理API - 创建、查询、更新运单信息
  version: 1.0.0

paths:
  /api/shipments:
    get:
      summary: 获取运单列表
      description: 分页查询运单列表，支持状态和时间过滤
      tags:
        - Shipments
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: 页码
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
          description: 每页数量
        - name: status
          in: query
          schema:
            type: string
            enum: [created, picked_up, in_transit, delivered, cancelled]
          description: 运单状态过滤
        - name: startDate
          in: query
          schema:
            type: string
            format: date
          description: 开始日期过滤
        - name: endDate
          in: query
          schema:
            type: string
            format: date
          description: 结束日期过滤
      responses:
        '200':
          description: 运单列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentListResponse'

    post:
      summary: 创建运单
      description: 创建新的运单记录
      tags:
        - Shipments
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShipmentRequest'
      responses:
        '201':
          description: 运单创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipment'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/shipments/{shipmentId}:
    get:
      summary: 获取运单详情
      description: 根据ID获取运单的详细信息
      tags:
        - Shipments
      security:
        - bearerAuth: []
      parameters:
        - name: shipmentId
          in: path
          required: true
          schema:
            type: string
          description: 运单ID
      responses:
        '200':
          description: 运单详情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentDetail'
        '404':
          description: 运单不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: 更新运单
      description: 更新运单信息
      tags:
        - Shipments
      security:
        - bearerAuth: []
      parameters:
        - name: shipmentId
          in: path
          required: true
          schema:
            type: string
          description: 运单ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateShipmentRequest'
      responses:
        '200':
          description: 运单更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipment'

    delete:
      summary: 取消运单
      description: 取消指定的运单
      tags:
        - Shipments
      security:
        - bearerAuth: []
      parameters:
        - name: shipmentId
          in: path
          required: true
          schema:
            type: string
          description: 运单ID
      responses:
        '200':
          description: 运单取消成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /api/shipments/{shipmentId}/status:
    patch:
      summary: 更新运单状态
      description: 更新运单的状态（如提货、在途、送达等）
      tags:
        - Shipments
      security:
        - bearerAuth: []
      parameters:
        - name: shipmentId
          in: path
          required: true
          schema:
            type: string
          description: 运单ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: 状态更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipment'

  /api/shipments/{shipmentId}/tracking:
    get:
      summary: 获取运单追踪信息
      description: 获取运单的实时GPS追踪和状态历史
      tags:
        - Tracking
      security:
        - bearerAuth: []
      parameters:
        - name: shipmentId
          in: path
          required: true
          schema:
            type: string
          description: 运单ID
      responses:
        '200':
          description: 追踪信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackingInfo'

components:
  schemas:
    CreateShipmentRequest:
      type: object
      required:
        - sender
        - senderAddress
        - receiver
        - receiverAddress
        - cargo
      properties:
        sender:
          $ref: '#/components/schemas/ContactInfo'
        senderAddress:
          $ref: '#/components/schemas/Address'
        receiver:
          $ref: '#/components/schemas/ContactInfo'
        receiverAddress:
          $ref: '#/components/schemas/Address'
        cargo:
          $ref: '#/components/schemas/CargoInfo'
        pickupTime:
          type: string
          format: date-time
          description: 预约提货时间
        estimatedDeliveryTime:
          type: string
          format: date-time
          description: 预计送达时间
        freight:
          type: number
          description: 运费
          example: 500.00
        specialInstructions:
          type: string
          description: 特殊要求
          example: "易碎品，小心轻放"

    UpdateShipmentRequest:
      type: object
      properties:
        driverId:
          type: string
          description: 分配的司机ID
        vehicleId:
          type: string
          description: 分配的车辆ID
        pickupTime:
          type: string
          format: date-time
          description: 提货时间
        estimatedDeliveryTime:
          type: string
          format: date-time
          description: 预计送达时间
        freight:
          type: number
          description: 运费

    UpdateStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [created, picked_up, in_transit, delivered, cancelled]
          description: 新状态
        notes:
          type: string
          description: 状态变更备注
        location:
          $ref: '#/components/schemas/GeoCoordinates'
        timestamp:
          type: string
          format: date-time
          description: 状态变更时间

    Shipment:
      type: object
      properties:
        id:
          type: string
          description: 运单ID
        shipmentNumber:
          type: string
          description: 运单号
          example: "WD202501270001"
        status:
          type: string
          enum: [created, picked_up, in_transit, delivered, cancelled]
          description: 运单状态
        sender:
          $ref: '#/components/schemas/ContactInfo'
        senderAddress:
          $ref: '#/components/schemas/Address'
        receiver:
          $ref: '#/components/schemas/ContactInfo'
        receiverAddress:
          $ref: '#/components/schemas/Address'
        cargo:
          $ref: '#/components/schemas/CargoInfo'
        driverId:
          type: string
          description: 司机ID
        driverName:
          type: string
          description: 司机姓名
        vehicleId:
          type: string
          description: 车辆ID
        vehiclePlateNumber:
          type: string
          description: 车牌号
        pickupTime:
          type: string
          format: date-time
          description: 提货时间
        estimatedDeliveryTime:
          type: string
          format: date-time
          description: 预计送达时间
        actualDeliveryTime:
          type: string
          format: date-time
          description: 实际送达时间
        freight:
          type: number
          description: 运费
        currency:
          type: string
          description: 货币单位
          example: "CNY"
        createdAt:
          type: string
          format: date-time
          description: 创建时间
        updatedAt:
          type: string
          format: date-time
          description: 更新时间

    ShipmentDetail:
      allOf:
        - $ref: '#/components/schemas/Shipment'
        - type: object
          properties:
            route:
              $ref: '#/components/schemas/Route'
            statusHistory:
              type: array
              items:
                $ref: '#/components/schemas/StatusChange'
              description: 状态变更历史

    ShipmentListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Shipment'
        pagination:
          $ref: '#/components/schemas/Pagination'

    ContactInfo:
      type: object
      required:
        - name
        - phone
      properties:
        name:
          type: string
          description: 联系人姓名
          example: "张三"
        phone:
          type: string
          description: 联系电话
          example: "13800138000"
        company:
          type: string
          description: 公司名称
          example: "北京物流有限公司"

    Address:
      type: object
      required:
        - street
        - city
        - province
        - country
      properties:
        street:
          type: string
          description: 街道地址
          example: "中关村大街1号"
        city:
          type: string
          description: 城市
          example: "北京市"
        province:
          type: string
          description: 省份
          example: "北京市"
        postalCode:
          type: string
          description: 邮政编码
          example: "100000"
        country:
          type: string
          description: 国家
          example: "中国"
        coordinates:
          $ref: '#/components/schemas/GeoCoordinates'

    GeoCoordinates:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
          description: 纬度
          example: 39.9042
        longitude:
          type: number
          minimum: -180
          maximum: 180
          description: 经度
          example: 116.4074

    CargoInfo:
      type: object
      required:
        - description
        - weight
        - quantity
        - unit
      properties:
        description:
          type: string
          description: 货物描述
          example: "电子产品"
        weight:
          type: number
          description: 重量（千克）
          example: 25.5
        volume:
          type: number
          description: 体积（立方米）
          example: 0.5
        quantity:
          type: integer
          description: 数量
          example: 10
        unit:
          type: string
          description: 单位
          example: "箱"
        value:
          type: number
          description: 货值（元）
          example: 5000.00
        specialRequirements:
          type: array
          items:
            type: string
          description: 特殊要求
          example: ["易碎", "防潮"]

    Route:
      type: object
      properties:
        id:
          type: string
          description: 路线ID
        startLocation:
          $ref: '#/components/schemas/GeoCoordinates'
        endLocation:
          $ref: '#/components/schemas/GeoCoordinates'
        totalDistance:
          type: number
          description: 总距离（千米）
        estimatedDuration:
          type: integer
          description: 预计耗时（分钟）
        actualDuration:
          type: integer
          description: 实际耗时（分钟）
        status:
          type: string
          enum: [planned, active, completed, paused]
          description: 路线状态

    StatusChange:
      type: object
      properties:
        id:
          type: string
          description: 状态变更ID
        status:
          type: string
          enum: [created, picked_up, in_transit, delivered, cancelled]
          description: 状态
        notes:
          type: string
          description: 备注
        location:
          $ref: '#/components/schemas/GeoCoordinates'
        address:
          type: string
          description: 地址描述
        timestamp:
          type: string
          format: date-time
          description: 变更时间
        updatedBy:
          type: string
          description: 操作人

    TrackingInfo:
      type: object
      properties:
        shipmentId:
          type: string
          description: 运单ID
        currentStatus:
          type: string
          description: 当前状态
        currentLocation:
          $ref: '#/components/schemas/GeoCoordinates'
        lastUpdateTime:
          type: string
          format: date-time
          description: 最后更新时间
        estimatedArrival:
          type: string
          format: date-time
          description: 预计到达时间
        gpsHistory:
          type: array
          items:
            $ref: '#/components/schemas/GPSPoint'
          description: GPS历史轨迹
        statusHistory:
          type: array
          items:
            $ref: '#/components/schemas/StatusChange'
          description: 状态变更历史

    GPSPoint:
      type: object
      properties:
        coordinates:
          $ref: '#/components/schemas/GeoCoordinates'
        timestamp:
          type: string
          format: date-time
          description: 时间戳
        speed:
          type: number
          description: 速度（km/h）
        heading:
          type: number
          description: 方向角（度）
        source:
          type: string
          enum: [g7_device, driver_app, manual]
          description: 数据来源

    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: 当前页码
        limit:
          type: integer
          description: 每页数量
        total:
          type: integer
          description: 总记录数
        pages:
          type: integer
          description: 总页数

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "操作成功"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: 错误代码
        message:
          type: string
          description: 错误描述

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT