// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjdiuujwzghrtphfjfgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqZGl1dWp3emdocnRwaGZqZmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDM4OTAsImV4cCI6MjA3NDUxOTg5MH0.A7X_cfmiTULXdjQEr5_OzFicXJF875tdhfuuN0dX0d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});